# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      build_semver:
        enabled: true

builders:
  build_semver:
    import: "package:build_semver/builder.dart"
    builder_factories: ["buildSemver"]
    build_extensions: {"pubspec.yaml": ["lib/src/version.dart"]}
    defaults:
      options:
        output: "lib/src/version.dart"
    build_to: source
    auto_apply: dependents
