name: build_semver
description: A builder for extracting a package version into code.
version: 1.0.0
repository: https://github.com/jtdLab/build_semver

environment:
  sdk: ^3.4.0

dependencies:
  build: ^2.1.0
  # Not imported in code, but used to constrain `build.yaml` requirements
  build_config: ^1.0.0
  pubspec_parse: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.0
  build_test: ^2.1.0
  build_verify: ^3.0.0
  checked_yaml: ^2.0.1
  dart_flutter_team_lints: ^3.0.0
  test: ^1.16.8
